### PR TITLE
fix: Update to available version of perfect-scrollbar

### PR DESCRIPTION
**Pull request by evsheffield**
It saddens me to be modifying the bower config of ancient repositories, but something must have happened that caused the previous bower version of perfect-scrollbar to vanish into the aether. That repo is, unsurprisingly, archived and deprecated, but there's still one last version that works. And poor PUMA needs it to install its bower dependencies.

### CODE REVIEW

**Comment by oxygenplug** [comment]
Any hope of having this reviewed and merged in? I'm finding myself in a scenario where this is a necessary fix.

**Comment by jtrussell** [comment]
If @evsheffield wrote it, that's good enough for me. Do you need a tag, @oxygenplug?

**Comment by oxygenplug** [comment]
I apologize if this is a silly question but would it be possible to tag this / make it a new release? Even after uninstalling all my packages with bower, cleaning bower's cache, and reinstalling it seems to want to pull the old version of perfect-scrollbar. I'm hoping that may fix it?

**Comment by jtrussell** [comment]
Sure thing, I'll tag a new version later today. Sorry, it's bean a little while since I've used Bower and I couldn't remember what was required to cut a new release.

**Comment by oxygenplug** [comment]
I don't blame you. Hoping to join the 'Been a while since I've used Bower' club myself ASAP haha. Thanks again!

**Comment by jtrussell** [comment]
ok, version - `0.2.6` should be up for grabs.

@evsheffield sorry for leaving this hanging so long. You've probably already got a fork but we could move this to an iVantage repo if you like.

**Comment by evsheffield** [comment]
Thanks for merging, @jtrussell! We've just been using a fork in the meantime, so no worries. I'm happy to leave ownership with you so as to not require any changes to folks' `bower.json` files, but if you'd rather not be on the hook feel free to toss it our way. 🤞 we shouldn't need to do much with this in the future.

**Pull request merged**
